# schema.yaml
on_screen_count: map(list(include('screen_config')), key=int())
global_failback: map(include('device'), key=str())

---

screen_config:
  map(any(include('device'), include('hooks')), key=str(), required=False)

device:
  resolution: str(required=False)
  frequency: int(required=False)
  primary: bool(required=False)
  left-of: str(required=False)
  disabled: bool(required=False)

hooks:
  post: list(str(), required=False)
  pre: list(str(), required=False)

